
-- [CALENDAR PROJECT] 회원 테이블 생성
CREATE TABLE CALENDAR_USER (
	USER_ID VARCHAR2(50) PRIMARY KEY NOT NULL,
	PASSWORD VARCHAR2(100),
	USERNAME VARCHAR2(50),
	NICKNAME VARCHAR2(50),
	USEREMAIL VARCHAR2(50),
	USERPHONE VARCHAR2(50),
	SIGNUP_DATE DATE DEFAULT CURRENT_DATE,
	AUTH CHAR(1) DEFAULT 'U',
	DROPOUT CHAR(1) DEFAULT 'N'
);

-- 회원 전체조회
SELECT *
	FROM CALENDAR_USER;

-- 회원가입 (전부기입)
INSERT INTO CALENDAR_USER (USER_ID, PASSWORD, USERNAME, NICKNAME, USEREMAIL, USERPHONE, SIGNUP_DATE, AUTH, DROPOUT)
	VALUES ('HIHI', 'HIHI', '하이', '하이01', 'hihi01@naver.com', '010-0000-0000', CURRENT_DATE, 'U', 'N');

-- 회원가입 (부분기입)
INSERT INTO CALENDAR_USER (USER_ID, PASSWORD, USERNAME, NICKNAME, USEREMAIL, USERPHONE)
	VALUES ('RAON', 'RAON', '라온', '', '', '');

-- 로그인
SELECT USER_ID, PASSWORD, USERNAME, NICKNAME, USEREMAIL, USERPHONE, SIGNUP_DATE, AUTH, DROPOUT
	FROM CALENDAR_USER 
	WHERE USER_ID = 'RAON' 
	AND PASSWORD = 'RAON'
	AND DROPOUT = 'N';
	
-- 아이디 중복검사
SELECT COUNT(*)
	FROM CALENDAR_USER
	WHERE USER_ID = 'RAON';
	
-- 아이디 찾기
SELECT USER_ID
	FROM CALENDAR_USER
	WHERE USEREMAIL = 'hihi01@naver.com';