
---------------------- * 테이블 생성 * ----------------------
-- REF : 댓글 그룹 / STEP : 댓글 구분(댓글, 대댓글), DEPTH : 댓글 깊이

-- BOARDTEST 테이블 생성
CREATE TABLE BOARDTEST (
	SEQ NUMBER PRIMARY KEY NOT NULL,
	ID VARCHAR2(20),
	TITLE VARCHAR2(200),
	CONTENT VARCHAR2(1000),
	CREATEAT DATE,
	DEPTH NUMBER,
	REF NUMBER,
	STEP NUMBER,	
	DELFLAG CHAR(1) DEFAULT 'N'
);

-- SEQUENCE TABLE 설정
CREATE SEQUENCE BOARDTEST_BO_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

-- CREATEAT 기본 설정값 변경
ALTER TABLE BOARDTEST MODIFY CREATEAT DATE DEFAULT CURRENT_DATE;
ALTER TABLE BOARDTEST MODIFY B_VIEWCOUNT NUMBER DEFAULT 0;

-- BOARDTEST 컬럼 추가
ALTER TABLE BOARDTEST ADD BO_WRITER VARCHAR2(200);
ALTER TABLE BOARDTEST ADD B_NO NUMBER; -- 게시판 넘버링
ALTER TABLE BOARDTEST ADD B_VIEWCOUNT NUMBER; -- 게시판 조회수


-- BOARDTEST 컬럼명 변경
ALTER TABLE BOARDTEST RENAME COLUMN SEQ TO BO_SEQ;
ALTER TABLE BOARDTEST RENAME COLUMN ID TO BO_WRITERID;

-- REPLYTEST 테이블 생성
CREATE TABLE REPLYTEST (
	RE_NO NUMBER PRIMARY KEY,
	BO_SEQ NUMBER,
	RE_CONTENT VARCHAR2(800),
	RE_WRITER VARCHAR2(200),
	RE_WIRTERID VARCHAR2(40),
	RE_CREATEAT DATE,
	RE_STEP NUMBER,
	RE_DEPTH NUMBER,
	RE_DELFLAG CHAR(1) DEFAULT 'N',
	CONSTRAINT FK_REPLYBOARD FOREIGN KEY (BO_SEQ) REFERENCES BOARDTEST(BO_SEQ)
);

---------------------- * 게시글 영역 * ----------------------

-- 게시글 입력
INSERT INTO BOARDTEST (B_SEQ, B_TITLE, B_CONTENT, B_WRITER, B_WRITERID, B_NO)
VALUES (BOARDTEST_BO_SEQ.NEXTVAL, '조회수 테스트', '조회수 테스트 진행중입니다...', '관리자', 'MANAGER', (SELECT NVL(MAX(B_NO) + 1, 0) AS B_NO FROM BOARDTEST));

-- 게시글 전체 조회
SELECT B_SEQ, B_NO, B_TITLE, B_CREATEAT, B_WRITER, B_DELFLAG, B_VIEWCOUNT  
	FROM BOARDTEST b 
	ORDER BY B_SEQ DESC;
	
-- 게시글 상세 조회
SELECT B_SEQ, B_WRITER, B_TITLE, B_CONTENT, TO_CHAR(B_CREATEAT, 'YYYY-MM-DD') AS B_CREATEAT  
	FROM BOARDTEST b 
	WHERE B_SEQ = 1;
	
-- 게시글 수정
UPDATE BOARDTEST 
	SET B_CONTENT  = '수정된 게시글입니다.',
		B_CREATEAT = TO_CHAR(CURRENT_DATE, 'YYYY-MM-DD') 
	WHERE B_SEQ = 1; 
	
-- 게시글 삭제
UPDATE BOARDTEST 
	SET B_DELFLAG = 'N'
	WHERE B_SEQ = 1;

-- 게시글 복구
UPDATE BOARDTEST 
	SET B_DELFLAG = 'N'
	WHERE B_DELFLAG = 'Y'
	AND B_SEQ = 1;

-- 조회수 업데이트
UPDATE BOARDTEST
SET B_VIEWCOUNT = B_VIEWCOUNT +1
WHERE B_SEQ = 27;
	
---------------------- * Pagination * ----------------------

-- 페이징 조회
SELECT B_SEQ, B_TITLE, B_WRITER, B_CREATEAT, B_DELFLAG
         FROM BOARDTEST
         ORDER BY B_SEQ DESC;


-- 총 게시글 갯수
SELECT COUNT(*)
	FROM BOARDTEST; 

-- 페이징 처리 후 게시글 조회 테스트 ver.1
SELECT B_SEQ, B_WRITER, B_TITLE, B_CONTENT, B_CREATEAT, B_DELFLAG, ROWNUM AS RN
     FROM (
         SELECT B_SEQ, B_WRITER, B_TITLE, B_CONTENT, B_CREATEAT, B_DELFLAG, ROWNUM AS RN
         FROM BOARDTEST
         ORDER BY B_SEQ DESC
     )    
     WHERE RN BETWEEN 1 AND 10;

    
-- 페이징 처리 후 게시글 조회 테스트 ver.2
SELECT B_SEQ, B_WRITER, B_TITLE, B_CONTENT, B_CREATEAT, B_DELFLAG, RN
FROM (
    SELECT B_SEQ, B_WRITER, B_TITLE, B_CONTENT, B_CREATEAT, B_DELFLAG, ROWNUM AS RN
    FROM (
        SELECT B_SEQ, B_WRITER, B_TITLE, B_CONTENT, B_CREATEAT, B_DELFLAG
        FROM BOARDTEST
        ORDER BY B_SEQ DESC -- 시간 내림차순, B_SEQ 내림차순으로 정렬
    )
)
ORDER BY RN DESC;

-- 페이징 처리 후 게시글 조회 테스트 ver.3
SELECT B_SEQ, B_WRITER, B_TITLE, B_CONTENT, B_CREATEAT, B_DELFLAG, ROWNUM AS RN
    FROM (
        SELECT B_SEQ, B_WRITER, B_TITLE, B_CONTENT, B_CREATEAT, B_DELFLAG,
               ROW_NUMBER() OVER (ORDER BY B_SEQ DESC) AS RN
        FROM BOARDTEST
        ORDER BY B_CREATEAT ASC -- createat 오름차순으로 정렬
    )
    WHERE RN BETWEEN 1 AND 10
	ORDER BY RN DESC;

-- 페이징 처리 후 게시글 조회 테스트 ver.4
SELECT *
FROM (
    SELECT B_SEQ, B_WRITER, B_TITLE, B_CONTENT, B_CREATEAT, B_DELFLAG, RN
    FROM (
        SELECT B_SEQ, B_WRITER, B_TITLE, B_CONTENT, B_CREATEAT, B_DELFLAG,
               ROW_NUMBER() OVER (ORDER BY B_SEQ DESC) AS RN
        FROM BOARDTEST
    )
)
WHERE RN BETWEEN 1 AND 10;

-- 페이징 처리 후 게시글 조회 테스트 ver.5
SELECT B_SEQ, B_NO, B_WRITER, B_TITLE, B_CONTENT, B_CREATEAT, B_DELFLAG
FROM BOARDTEST
WHERE B_NO BETWEEN 1 AND 10
ORDER BY B_NO DESC;


WHERE B_NO BETWEEN 1 AND 10
ORDER B_NO DESC;


-- 페이징 처리 후 게시글 조회 테스트 ver.6
SELECT B_SEQ, B_NO, B_WRITER, B_TITLE, B_CONTENT, B_CREATEAT, B_DELFLAG
FROM (
    SELECT B_SEQ, B_NO, B_WRITER, B_TITLE, B_CONTENT, B_CREATEAT, B_DELFLAG
    FROM BOARDTEST
    ORDER BY B_NO DESC
) 
WHERE B_NO BETWEEN 1 AND 10;












