
---------------------- * 테이블 생성 * ----------------------
-- REF : 댓글 그룹 / STEP : 댓글 구분(댓글, 대댓글), DEPTH : 댓글 깊이

-- BOARDTEST 테이블 생성
CREATE TABLE BOARDTEST (
	SEQ NUMBER PRIMARY KEY NOT NULL,
	ID VARCHAR2(20),
	TITLE VARCHAR2(200),
	CONTENT VARCHAR2(1000),
	CREATEAT DATE,
	DEPTH NUMBER,
	REF NUMBER,
	STEP NUMBER,	
	DELFLAG CHAR(1) DEFAULT 'N'
);

-- SEQUENCE TABLE 설정
CREATE SEQUENCE BOARDTEST_BO_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

-- CREATEAT 기본 설정값 변경
ALTER TABLE BOARDTEST MODIFY CREATEAT DATE DEFAULT CURRENT_DATE;

-- BOARDTEST 컬럼 추가
ALTER TABLE BOARDTEST ADD BO_WRITER VARCHAR2(200);

-- BOARDTEST 컬럼명 변경
ALTER TABLE BOARDTEST RENAME COLUMN SEQ TO BO_SEQ;
ALTER TABLE BOARDTEST RENAME COLUMN ID TO BO_WRITERID;

-- REPLYTEST 테이블 생성
CREATE TABLE REPLYTEST (
	RE_NO NUMBER PRIMARY KEY,
	BO_SEQ NUMBER,
	RE_CONTENT VARCHAR2(800),
	RE_WRITER VARCHAR2(200),
	RE_WIRTERID VARCHAR2(40),
	RE_CREATEAT DATE,
	RE_STEP NUMBER,
	RE_DEPTH NUMBER,
	RE_DELFLAG CHAR(1) DEFAULT 'N',
	CONSTRAINT FK_REPLYBOARD FOREIGN KEY (BO_SEQ) REFERENCES BOARDTEST(BO_SEQ)
);

---------------------- * 게시글 영역 * ----------------------

-- 게시글 입력
INSERT INTO BOARDTEST (BO_SEQ, BO_TITLE, BO_CONTENT, BO_WRITER)
VALUES (BOARDTEST_BO_SEQ.NEXTVAL, '두번째 게시글입니다', '게시글 작성중...', '코코아');

-- 게시글 전체 조회
SELECT BO_SEQ, BO_TITLE, BO_WRITER, BO_CREATEAT, BO_DELFLAG  
	FROM BOARDTEST b 
	ORDER BY BO_SEQ DESC;
	
-- 게시글 상세 조회
SELECT BO_SEQ, BO_WRITER, BO_TITLE, BO_CONTENT, TO_CHAR(BO_CREATEAT, 'YYYY-MM-DD') AS BO_CREATEAT  
	FROM BOARDTEST b 
	WHERE BO_SEQ = 1;
	
-- 게시글 수정
UPDATE BOARDTEST 
	SET BO_CONTENT  = '수정된 게시글입니다.',
		BO_CREATEAT = TO_CHAR(CURRENT_DATE, 'YYYY-MM-DD') 
	WHERE BO_SEQ = 1; 
	
-- 게시글 삭제
UPDATE BOARDTEST 
	SET BO_DELFLAG = 'N'
	WHERE BO_SEQ = 1;

-- 게시글 복구
UPDATE BOARDTEST 
	SET BO_DELFLAG = 'N'
	WHERE BO_DELFLAG = 'Y'
	AND BO_SEQ = 1;