

-- 파일 전체조회
SELECT F_SEQ, B_SEQ, B_WRITER, ORIGIN_FILENAME, STORED_FILENAME, FILE_SIZE, F_REGDATE, F_DELFLAG
	FROM FILEBOARD 
	ORDER BY B_SEQ DESC;
	
-- 게시물 별 파일 상세조회
SELECT B_SEQ, F_SEQ, ORIGIN_FILENAME, STORED_FILENAME, FILE_SIZE, F_REGDATE, F_DELFLAG
	FROM FILEBOARD f 
	WHERE B_SEQ = 58;
	
-- 첨부파일 등록
INSERT INTO F_SEQ, B_SEQ, B_WRITER, ORIGIN_FILENAME, STORED_FILENAME, FILE_SIZE, F_REGDATE, F_DELFLAG
	VALUES (SELECT NVL(MAX(F_SEQ) + 1, 0) AS F_SEQ FROM FILEBOARD), 189, B_WRITER, 'ORIGIN_FILENAME', STORED_FILENAME, 300, CURRENT_DATE, 'N';
	
-- 첨부파일 시퀀스 (F_SEQ)
-- NVL(MAX(F_SEQ), 0)를 사용하여 테이블이 비어 있을 경우 NULL 대신 0을 반환
SELECT NVL(MAX(F_SEQ) + 1, 0) AS F_SEQ
	FROM FILEBOARD ;
	
-- FILD_DATA 컬럼 추가
ALTER TABLE FILEBOARD ADD FILE_DATA BLOB;